### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by nullkk** [liangjingkanji/StateLayout#1]
有java版本吗 kotlin在java里面不通用
<img width="909" alt="WX20200519-110200@2x" src="https://user-images.githubusercontent.com/20369464/82279912-362e5c80-99c0-11ea-84f6-d9b2a7a34ad6.png">

**Comment by xtgadw** [comment]
StateConfig.INSTANCE.

**Comment by Krosxx** [comment]
StateConfig 类的函数上可以加个 @JvmStatic 注解

**Comment by liangjingkanji** [comment]
好的, 我没有及时收到消息通知抱歉

update 1.1.0
