### ISSUE TITLE
嵌套NestedScrollView时,内容将不能正常显示

### ISSUE THREAD

**Issue by Petterpx** [liangjingkanji/StateLayout#10]
当内容视图为NestedScrollView时,不能正常显示,必须将StateLayout作为Ns子布局才行

**Comment by liangjingkanji** [comment]
请详细描述下不正常显示

**Comment by Petterpx** [comment]
xml中使用，StateLayout内容视图是NestedScrollView时时, 代码中使用showContent()方法，ns的子布局不能正常显示。必须改为 NestedScrollView包含StateLayout ,原ns内布局移到Statelayout中, 才可以正常显示。如图
![image](https://user-images.githubusercontent.com/41142188/133402243-dd7e3d80-f103-4e23-bd7a-0ddaaf59fbfe.png)

**Comment by Petterpx** [comment]
代码问题，尴尬
