### ISSUE TITLE
动态计算布局内 图片的位置，这个不好扩展哇

### ISSUE THREAD

**Issue by ljackChen001** [liangjingkanji/StateLayout#13]
动态计算布局内 图片的位置，这个不好扩展哇

**Comment by liangjingkanji** [comment]
你是想实现骨架图缺省页?

文档有提及该属于加载动画, 推荐实现方式: [骨骼动画](https://liangjingkanji.github.io/StateLayout/animation/#_2)

**Comment by ljackChen001** [comment]
不是的，我们这边需要动态计算 ，空布局/loading布局 等等..  内 视图资源 占用整个状态页面的比例

**Comment by ljackChen001** [comment]
需要在addView 之前就去计算位置

**Comment by liangjingkanji** [comment]
你在`addView`之后计算再次修改尺寸不是一样吗?

我也不清楚计算占用缺省页比例有什么用处

**Comment by ljackChen001** [comment]
![image](https://user-images.githubusercontent.com/13534229/148038148-7c02180f-648a-4dd7-aa12-fd96e8aec498.png)
例如 loadsir  我可以在 EmptyCallback 去动态计算

**Comment by ljackChen001** [comment]
还有  比如我资源文件用到了Lottie 动画 我需要手动去控制 ，整个好像也不是很好扩展

**Comment by liangjingkanji** [comment]
提供onError/onLoading等生命周期函数可以做动画, 你也可以在里面重新修改View尺寸

**Comment by ljackChen001** [comment]
感觉还是提供CallBack 扩展更加方便一点

**Comment by liangjingkanji** [comment]
你是希望拦截创建View的回调, 还是说希望通过添加多个自定义Callback来显示自定义缺省页

**Comment by ljackChen001** [comment]
类似LoadSir 多个自定义Callback  这样写法 可以在各自的CallBack 做很多操作，而且也可以配合viewbinding一起使用

**Comment by liangjingkanji** [comment]
那不得忽略掉原来的showEmpty/showError等布局配置

**Comment by ljackChen001** [comment]
对呀  各自的布局就写着各自的callback里，这个看你嘛，我目前使用LoadSir 实现了这个功能

**Comment by liangjingkanji** [comment]
你看现在如何
```kotlin
// 注册缺省页工厂
registerSate(StateFactory)

// 显示注册的缺省页
showState(StateFactory::class.java)
```

StateFactory提供函数

```kotlin
// 创建视图
fun onCreateView():View

// 视图被Add
fun onAttach()

// 视图被Remove
fun onDetach()
```

你认为上一个缺省页是隐藏还是remove掉更好(原来都是隐藏)

**Comment by ljackChen001** [comment]
我感觉直接 remove 掉比较好

**Comment by ljackChen001** [comment]
https://github.com/Zhao-Yan-Yan/MultiStatePage 这个库是直接remove的 但是感觉没你代码写的风骚

**Comment by liangjingkanji** [comment]
感觉这个提议不错可以添加上

**Comment by ljackChen001** [comment]
老哥稳

**Comment by ZhZhZhen** [comment]
强东哥牛蛙，希望可以快点用到最新的

**Comment by liangjingkanji** [comment]
好的!

**Comment by liangjingkanji** [comment]
@ljackChen001 

新的功能在`dev`分支, 试下如何

依赖为

```groovy
implementation 'com.github.liangjingkanji:StateLayout:1c437c51a4'
```

**Comment by ljackChen001** [comment]
刚刚试了一下  动态布局是OK的   就是会闪一下   布局先出现在原位置  然后闪一下 才是正确的位置 @liangjingkanji

**Comment by ljackChen001** [comment]
你这个onAttach 放在addView 之前应该就不会出现这种现象了

**Comment by ljackChen001** [comment]
我加个动画就完美了

**Comment by ljackChen001** [comment]
调用View.showContent 会报错 java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup

**Comment by liangjingkanji** [comment]
> 刚刚试了一下 动态布局是OK的 就是会闪一下 布局先出现在原位置 然后闪一下 才是正确的位置 @liangjingkanji
你是在`onAttach`里面修改位置的吗?

**Comment by ljackChen001** [comment]
对的  使用全局配置 调用了view.showLoading()  再调用其他的view.showxxx 都会空指针，

**Comment by liangjingkanji** [comment]
onAttach是已经添加到缺省页容器StateLayout后的回调(添加就会显示在手机屏幕), 你在这里修改位置不就和onError等没区别吗?
你应该在`onCreate`里面修改吧?

**Comment by liangjingkanji** [comment]
content缺省页应该也得有个StateFactory, 但是没有onCreate函数

**Comment by liangjingkanji** [comment]
你说的`View.showContent`中的View是什么? 是StateLayout吗? 
Demo中不是很正常吗? 你是否没有配置缺省页? 可以的话Fork仓库复现发我地址吧, 因为我目前无法复现

**Comment by ljackChen001** [comment]
> onAttach是已经添加到缺省页容器StateLayout后的回调(添加就会显示在手机屏幕), 你在这里修改位置不就和onError等没区别吗? 你应该在`onCreate`里面修改吧?
 我试过了 都可以  添加个动画就行

**Comment by ljackChen001** [comment]
> 你说的`View.showContent`中的View是什么? 是StateLayout吗? Demo中不是很正常吗? 你是否没有配置缺省页? 可以的话Fork仓库复现发我地址吧, 因为我目前无法复现

公司不能上传任何东西，View 指的是 SmartRefreshLayout，使用的全局配置，XML没有增加StateLayout, 如果都只是单独使用某一个是没有问题，这几个状态连起来一起用就会有问题，showLoading（）正常 -->showEmpty()/showError()/showContent()  state()中的parent  就会空指针

**Comment by liangjingkanji** [comment]
你不会是反复调用`state()`函数吧?
Demo按照`showLoading（）正常 -->showEmpty()/showError()/showContent()`有问题吗?

**Comment by liangjingkanji** [comment]
前阵子忽略了这个仓库抱歉

最新版本`1.3.1`新增StateChangedHandler来实现完全自定义缺省页切换
无论是缺省页动态布局参数, 缺省页切换隐藏还是删除都完全可以自定义处理
