### ISSUE TITLE
东哥，StateLayout在CoordinatorLayoutFragment中该怎么使用

### ISSUE THREAD

**Issue by hlla** [liangjingkanji/StateLayout#14]
BRV的[CoordinatorLayoutFragment](https://github.com/liangjingkanji/BRV/blob/master/sample/src/main/java/com/drake/brv/sample/ui/fragment/CoordinatorLayoutFragment.kt)该怎么结合StateLayout呢，空布局没法滑动了，如果在StateLayout外层加个NestedScrollView, StateLayout内的SmartRefresh就无法上拉加载更多了

**Comment by liangjingkanji** [comment]
给你的空布局的xml中套一层`NestedScrollView `, 而不是给StateLayout套

**Comment by liangjingkanji** [comment]
关于你这个问题我会收录到使用文档中 👍

**Comment by ysy950803** [comment]
> 给你的空布局的xml中套一层`NestedScrollView `, 而不是给StateLayout套

牛逼，果然可以了。
