### ISSUE TITLE
屏幕旋转，报ID重复异常

### ISSUE THREAD

**Issue by zzh3321** [liangjingkanji/StateLayout#16]
屏幕发生旋转时报错
`java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.recyclerview.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/rv_list. Make sure other views do not use the same id.`

看了下源码View.state()方法中
`val stateLayout = StateLayout(context)`
`stateLayout.id = id`

**Comment by liangjingkanji** [comment]
好的我修复下

**Comment by liangjingkanji** [comment]
文档介绍是推荐在XML中定义的, 如果你代码配置那么只能自己处理恢复判断, 比如判断saveInstance不为null才执行`state()`
