### ISSUE TITLE
库无法导入

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/StateLayout#17]
无法添加远程依赖 

Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.liangjingkanji:StateLayout:1.3.3
Could not get resource 'https://jitpack.io/com/github/liangjingkanji/StateLayout/1.3.3/StateLayout-1.3.3.aar'.
Could not HEAD 'https://jitpack.io/com/github/liangjingkanji/StateLayout/1.3.3/StateLayout-1.3.3.aar'.
The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.3.3/userguide/build_environment.html#gradle_system_properties
Remote host terminated the handshake
SSL peer shut down incorrectly

**Comment by liangjingkanji** [comment]
是不是没有添加
```groovy
allprojects {
    repositories {
        // ...
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by SaltedFish-Extreme** [comment]
> 是不是没有添加

添加了，你的Channel框架都能正常使用

**Comment by liangjingkanji** [comment]
demo能否正常运行

**Comment by SaltedFish-Extreme** [comment]
> demo能否正常运行

可以

**Comment by liangjingkanji** [comment]
BRV最新版本也在依赖StateLayoutv1.3.3你有问题吗?

**Comment by SaltedFish-Extreme** [comment]
> BRV最新版本也在依赖StateLayoutv1.3.3你有问题吗?

BRV最新版导入没问题，奇怪的是把BRV导入注释掉再导入这个就没问题了😂也可能是公司网络环境的问题吧
