### ISSUE TITLE
RecyclerView搭配StateLayout的问题

### ISSUE THREAD

**Issue by ChawLoo** [liangjingkanji/StateLayout#18]
RecyclerView在set数据前state()绑定，先loading，再使用Brv进行数据绑定后，showContent方法调用后 无法显示数据

**Comment by liangjingkanji** [comment]
不知道你看过`state()`这个方法注释没, 反复调用会反复创建, 我建议你在XML布局中声明`StateLayout`不要使用该方法, 使用方法可读性太差

我估计是你调用`showContent`的StateLayout对象不是你显示在最上面的视图导致的问题(也就是你给一个rv包了好几层StateLayout布局)

**Comment by liangjingkanji** [comment]
考虑到总是有人对一个视图对象反复调用`state()`, 我现在将`state()`废弃(警告等级), 重名为`createStateLayout()`

**Comment by ChawLoo** [comment]
> 不知道你看过`state()`这个方法注释没, 反复调用会反复创建, 我建议你在XML布局中声明`StateLayout`不要使用该方法, 使用方法可读性太差
> 
> 我估计是你调用`showContent`的StateLayout对象不是你显示在最上面的视图导致的问题(也就是你给一个rv包了好几层StateLayout布局)

有一点没说明，我state()没有放在Rv里面，是放在外面的，所以不存在反复调用的情况，state后，先showLoading，然后rv加载数据，加载完后  showContent,但是RV的数据没有显示

**Comment by ChawLoo** [comment]
> 考虑到总是有人对一个视图对象反复调用`state()`, 我现在将`state()`废弃(警告等级), 重名为`createStateLayout()`

这个问题，其实我个人相对于布局中添加还是更喜欢代码中去创建

**Comment by liangjingkanji** [comment]
直接fork仓库复现吧，不用猜来猜去

**Comment by liangjingkanji** [comment]
代码创建会让项目可读性差，能xml还是xml吧，问题也少

**Comment by ChawLoo** [comment]
> 直接fork仓库复现吧，不用猜来猜去

我写个小demo  先研究一下，确认一下问题，问题先关了好了，确认完再来叨唠东哥
