### ISSUE TITLE
请问如果自定义一个布局完全不同于四种预设状态的缺省页？

### ISSUE THREAD

**Issue by lindroy** [liangjingkanji/StateLayout#19]
作者你好，我看文档里面的自定义似乎只是改变某一个缺省页布局上细微差别（比如显示服务器返回的不同错误），但是现在我想显示一个未登录状态的页面，需要重新写一个布局layout_unlogin.xml（预设的四个缺省页布局已经有了），那么如果将这个布局（相当于第五个布局）显示出来呢？

**Comment by liangjingkanji** [comment]
有`tag`标签以及`onError`等回调, 你都不知道如何显示不同的视图吗?

有视图对象你想显示什么内容都行的吧

甚至你还可以自定义StateChangedHandler来决定是删除还是隐藏视图

**Comment by lindroy** [comment]
可能是我理解不对，我理解是配置时只能添加四种缺省页，这四个布局是提前添加好，但是现在我有第五个跟这四个都不一样的布局，这样就有点不知道怎么操作了。

**Comment by liangjingkanji** [comment]
你固执认为四个状态就是四个layout, layout不能addView或者removeView亦或直接加载不同图片或者文字吗?

**Comment by liangjingkanji** [comment]
StateLayout缺省页本质就是在`StateChangedHandler`添加不同的视图对象而已, 你完全可以自定义去添加

但是我认为`OnError`就能满足

新增文档: [多状态](https://liangjingkanji.github.io/StateLayout/multi-state/)

**Comment by liangjingkanji** [comment]
任何状态都是根据这四种状态扩展延伸, 加个`tag`来区分展示很难理解吗? 你有使用过Hook或者OkHttp的拦截器等操作吗?

如果还不能理解本问题将关闭, 因为这已经是无效沟通了

**Comment by lindroy** [comment]
你的意思是根据不同的tag然后就可以在某个状态，比如error的视图中addView或者removeView了是吗？

**Comment by liangjingkanji** [comment]
是的

**Comment by liangjingkanji** [comment]
StateChangedHandler你看了没有? 直接在里面addView一个和error完全没关系的View也行, 请仔细阅读文档

**Comment by lindroy** [comment]
我之前也写过类似的库，不过我思路跟你的有点不一样，我的做法是每个缺省页（包括自定义的）搭配一个layout和一个state，用的时候根据state的值来show不同的缺省页哈哈。我先写写看，写出个例子就好理解了。

**Comment by liangjingkanji** [comment]
你的那种做法我认为不利于封装, 因为那拦截器就无法考虑到所有状态, 我认为无论是何种缺省页状态都是基于四种状态延伸

你要实现什么未登录已登录状态, 对于这种页面状态我还是推荐使用Fragment, 缺省页只是简单的高复用视图状态, 不要过度依赖导致项目复杂难懂
