### ISSUE TITLE
建议新增一个显示弹窗的方法

### ISSUE THREAD

**Issue by for7GG** [liangjingkanji/StateLayout#20]
state.showLoadingDialog()

**Comment by liangjingkanji** [comment]
这和缺省页有什么关系? 你都弹窗了还需要缺省页干什么

Android8开始谷歌废弃ProgressDialog, 因为不推荐加载对话框阻断用户焦点

**Comment by liangjingkanji** [comment]
想要自动显示加载对话框可以去看下[Net的自动加载框](https://liangjingkanji.github.io/Net/auto-dialog/)

**Comment by for7GG** [comment]
> 

是这样的，有时候用户点击刷新按钮，此时全屏展示一个加载框不合适吧

**Comment by liangjingkanji** [comment]
你这个需求不属于缺省页的范畴, 你阅读我上面发的文章就懂了

**Comment by for7GG** [comment]
明白你的意思，关键有切换状态的需求，不加也行，我本地改下代码吧

**Comment by liangjingkanji** [comment]
状态和缺省页两码事, 状态我建议用Fragment
