### ISSUE TITLE
提个问题。关于error过后的重试问题

### ISSUE THREAD

**Issue by Lemniscate317** [liangjingkanji/StateLayout#22]
你像我在项目中有两套loading。我通过传对象来判断要用哪套loading。现在问题来了，error过后重试的时候，loading的信息是null,是被消除掉的。所以我在想是否提供一个选项或者别的方式去实现保留态之类的

**Comment by liangjingkanji** [comment]
这个问题考虑过, 当初认为这属于特殊需求可以自己实现点击重试来判断

**Comment by liangjingkanji** [comment]
但我现在认为对于你这种需求可能保存上个状态信息来判断当前状态`tag`可能比较好

**Comment by liangjingkanji** [comment]
dev分支我已经修改好了你可以试下是不是你想要的效果

**Comment by Lemniscate317** [comment]
作者速度真快。我粗略测试了一下，保留了上一次的状态，是符合我的场景的。感谢

**Comment by liangjingkanji** [comment]
已发布`1.3.10`解决此问题

欢迎阅读源码共同参与
