### ISSUE TITLE
view会重复显示

### ISSUE THREAD

**Issue by huangbiao666** [liangjingkanji/StateLayout#24]
![image](https://user-images.githubusercontent.com/44941185/201463413-fce75489-c616-4d7f-9294-9f9c960dead1.png)
当有网时请求接口，显示empty视图，然后我主动断网请求接口，显示Error视图，再开网请求接口，我只显示空empty视图，但是Error视图还在，重叠在一起了，不知道什么原因（我主动同时显示empty 和 error，都不是同时展示），请指点一下
![image](https://user-images.githubusercontent.com/44941185/201464563-c7c2822b-c6c6-4d48-8d7f-68c7a6360ba1.png)

**Comment by liangjingkanji** [comment]
是否使用`StateChangedHandler`? 能否fork仓库在demo复现(fork按钮在started按钮旁边)?

**Comment by huangbiao666** [comment]
![image](https://user-images.githubusercontent.com/44941185/201562720-5560f7a8-fabb-4ad6-a080-02be77b68741.png)
没有使用StateChangeHandler

**Comment by huangbiao666** [comment]
就算我加上FadeStateChangeHandler()，还是一样的效果

**Comment by huangbiao666** [comment]
发现是没有设置loading view，导致无法隐藏上一个empty View, showStatus报异常了

**Comment by liangjingkanji** [comment]
那就是解决了吗

**Comment by huangbiao666** [comment]
![image](https://user-images.githubusercontent.com/44941185/201573094-ae77929d-787b-46ca-b99b-2849b6e801ae.png)

**Comment by liangjingkanji** [comment]
欢迎共同参与本开源项目

**Comment by huangbiao666** [comment]
我的疑问是，为什么一定要设置Loading呢，如果不设置，这种情况就一定会出现

**Comment by huangbiao666** [comment]
![image](https://user-images.githubusercontent.com/44941185/201573310-998c8bce-fade-4f42-974c-3033a17f38d5.png)

**Comment by liangjingkanji** [comment]
不设置loading_layout你怎么`showLoading()`?

**Comment by huangbiao666** [comment]
因为我们是全屏居中的一个loading Dialog样式

**Comment by huangbiao666** [comment]
能不能把刷新时，强制显示 showStatus(LOADING, tag) 的逻辑给改一下

**Comment by liangjingkanji** [comment]
> 因为我们是全屏居中的一个loading Dialog样式

1. 使用`showLoading()`并指定参数`silent=true`即可实现你的需求(多看注释文档)
2. 或者你设置一个空的`layout_loading`也可以, 另外谷歌官方不建议你通过Dialog阻断用户交互(这也是为什么ProcessDialog被废弃的原因)

**Comment by liangjingkanji** [comment]
另外你截图贴的几乎完全是无意义代码, 你九成以上代码是在判断更多页/刷新数据/显示缺省页

建议你尝试下BRV和Net减少你的`模板代码`完全自动化处理

**Comment by huangbiao666** [comment]
好的，谢谢
