### ISSUE TITLE
xml 嵌套recyclerview 没生效

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/StateLayout#25]
![图片](https://user-images.githubusercontent.com/28262649/203216880-f7e21d15-245f-4d9c-9c8c-2993268394ae.png)

![图片](https://user-images.githubusercontent.com/28262649/203216929-6bdb3c3f-3e7e-4fc2-a534-92e2cc0b2fe5.png)

这样写，加载的内容不显示，有什么问题嘛？

**Comment by liangjingkanji** [comment]
PageRefreshLayout具备StateLayout功能不需要再写一遍, 你最外层的ConstraintLayout也是多余的

**Comment by liangjingkanji** [comment]
你的代码太凌乱, 看不懂写的什么东西, 建议你多看demo因为BRV/Net支持自动分页, 根本不需要你调用`finishRefresh()`或者`showContent()`

**Comment by lastzhou** [comment]
![Uploading 图片.png…]()

这有点狠啊，要3个页面全部配齐才能有缺省页面功能，如果我只想要空页面？

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/203274059-6ca3c6b6-245b-460c-9ed3-16b9cf2cc591.png)
![图片](https://user-images.githubusercontent.com/28262649/203274183-3b7d39a7-0e17-4012-8a15-1558a8438fb8.png)

我在断网的情况下，如果不写这句，会出现
1，缺省页不显示
2，PageRefreshLayout 的loading 没关闭，一直转

大佬，有考虑断网，或者关闭网络，缺省页的处理？

**Comment by liangjingkanji** [comment]
在demo/文档中, 要求`onRefesh`中使用`scope`才会自动处理缺省页, 而不是`scopeNetLife`, 请仔细阅读文档/demo, 或者查看函数注释

**Comment by liangjingkanji** [comment]
> 这有点狠啊，要3个页面全部配齐才能有缺省页面功能，如果我只想要空页面？

你都赋值成空页面layout不就行了, 反正你也不用你还需要在乎赋值的什么布局吗?

**Comment by lastzhou** [comment]
哎，不知道，大佬有这么优秀
