### ISSUE TITLE
骨骼动画

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/StateLayout#26]
![图片](https://user-images.githubusercontent.com/28262649/203912847-7eebaf1a-31a5-403e-b303-5324079e9884.png)
![图片](https://user-images.githubusercontent.com/28262649/203912941-3a96e6b5-e19f-4cfd-b679-d74a70146147.png)

如果我要根据 item 布局，来创建自定义的骨骼动画，该怎么做？

**Comment by liangjingkanji** [comment]
没见过列表item做骨骼动画的，我觉得你应该理解有误

**Comment by liangjingkanji** [comment]
如果真的要做你只能自己研究了，我也不会

**Comment by lastzhou** [comment]
不是我之前用过这样框架，所以问下

**Comment by lastzhou** [comment]
我以前用过这样的框架，所以问下

**Comment by liangjingkanji** [comment]
StateLayout是一个View, 本质上和TextView没区别

至于你说Item做骨骼图, 我觉得太愚蠢, 我也没写过, 无法帮助你, 你可以用以前用过的框架思路写(本框架没有自定义rv)
