### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by yuzhiqiang1993** [liangjingkanji/StateLayout#27]
接入leakcanary后报内存泄漏，
![661672021126_ pic](https://user-images.githubusercontent.com/18605757/209491051-f904b398-1b41-4357-90bf-b4d5bbd9e048.jpg)

应该是isNetworking()中的context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager这行代码导致的。

<img width="809" alt="image" src="https://user-images.githubusercontent.com/18605757/209490932-496b647f-c64a-49d5-a5ef-51a2e621c31d.png">

改成
`
  val connectivityManager =
            context.applicationContext.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
`
后再次测试未报内存泄漏，仅供参考.

**Comment by liangjingkanji** [comment]
参考可以, 如果能参与项目发起pr更好, 因为这是属于你的贡献
