### ISSUE TITLE
重复调用showXXX不触发onXXX回调

### ISSUE THREAD

**Issue by maydaynicko** [liangjingkanji/StateLayout#29]
我需求是empty有好几种状态，我想根据不同场景显示不同的empty layout，根据传入tag去做逻辑，但是发现重复调用showEmpty时无法触发onEmpty回调

**Comment by maydaynicko** [comment]
看源码是判断了status跟上次相同就不处理了，是否应该再判断一下tag

**Comment by liangjingkanji** [comment]
对于你这种会看源码还能给出建议的我很看好你

我也认为应该如此，是第一作者考虑不周全
