### ISSUE TITLE
关于增加标题栏的显示

### ISSUE THREAD

**Issue by Lanxiong** [liangjingkanji/StateLayout#30]
你好 当前情况下 如果默认要显示标题栏 
只能先增加一层布局 比如线性布局 
上面标题栏 下面stateLayout 
而statelayout里面也只能一个子view 
又要套一层 加上statelayout自己 
就是布局起码三层打底

之前自己写过类似封装
标题栏一个viewgroup
内容区域一个viewgoup
是增加了一个自定义属性contenId 
来指定内容区域的viewgroup进行动态显示隐藏
这样可以默认显示出标题栏
可以减少一层

如果未指定 则强制只能一个子view
源码里每个类我都仔细看了
如果加上这个 没什么影响
不知道是否考虑不周？

**Comment by Lanxiong** [comment]
这里的showError方法 和 
PageRefreshLayout的showError方法不一样   
那边多了一个参数控制更合理    
这里的不管是否已经loaded 
只要showError 就会强制替换页面   
虽然外部调用也可以控制  
要是加个参数比较合理  
控制一下是否忽略loaded

**Comment by liangjingkanji** [comment]
## 不考虑

理由如下

1. 标题栏千变万化, 是无法封装的存在, 不仅仅是你想的一个标题一个箭头那么简单, 甚至可能需要联动列表, 我并不推荐去过渡封装标题栏, 这点可以从我另一个库`Engine`中的`EngineToolbarActivity`可以看出来我很反感去过渡封装标题栏

2. 仅仅是减少一层嵌套(而且是减少FrameLayout嵌套)在性能上微乎其微, 但是业务和扩展性上降低很多, 我是很反感这种为了`不存在的`性能提升而去写垃圾代码

> 所以缺省页永远不会去考虑标题栏

## 封装标题栏我的看法

对于标题栏我很反感某些人写一个控件然后写上所有标题/副标题/左图标/右图标, 然后通过开关来显示隐藏, 我认为这些人都是完全不考虑UI设计师的创造力的人

1. 我认为实现一个`BaseToolBarActivity`去展示一个默认标题栏. 每个项目都实现一个即可, 既不麻烦也不会无法扩展
2. 如果不需要默认标题栏或者甚至标题栏就实现`BaseActivity`

**Comment by liangjingkanji** [comment]
关于你提的二个问题这是因为`PageRefreshLayout`的刷新可能是`autoRefresh`下拉刷新而不是`showLoading`的缺省页刷新, 这个时候即使不显示错误缺省页他也是有内容展示的

而且`StateLayout`只存在`showLoading`, 在showLoading加载缺省页的情况下不存在`showError`无效的情况, 因为无效的话就代表要一直显示`加载中缺省页`那是非常不合理的

**Comment by Lanxiong** [comment]
https://user-images.githubusercontent.com/29808828/230599833-23372482-91a7-4b93-9feb-9fe403795706.MOV


好的 关于标题的我理解你了 

第二个问题
不好意思可能我没有表达清楚

看视频 刚开始的状态是已经成功加载了
此时 status=CONTENT,loaded=true

我再次刷新一下 接口报错
那我肯定是这么判断

if(!loaded){
    showError()
}

如果不加判断 直接showError() 会显示errorLayout
但是已经loaded=true 已经有可展示数据了 显示errorLayout不合理了

但你其他issue下面说 loaded是给内部用的 外面最好不用
所以是不是 showError()加一个参数比较好 类似

showError(xxx:XXXX,ignoreLoaded:Boolean=true){
    
    if (!ignoreLoaded&&loaded){
        return
    }
    //走原来逻辑
}

**Comment by liangjingkanji** [comment]
你视频中是下拉刷新, 使用的应该是PageRefreshLayout, 而它的showError内部已经默认判断是否loaded成功过, 如果成功过并不会展示errorLayout

我不明白你问StateLayout干什么, 你自己看清楚我说的第二点的内容

我猜测这个用户页面的下拉刷新是你自己写的(非PageRefreshLayout), 然后你在配合StateLayout一起使用, 那么这种情况请自己判断是否loaded过, 因为默认情况StateLayout只会考虑`showLoading`情况下showError该如何显示. 
框架不会考虑所有情况只会考虑绝大部分情况, 你已经自己处理下拉刷新就自己处理到底

**Comment by liangjingkanji** [comment]
如果你使用Net网络请求框架压根不需要调用`showError`等方法, 全是自动化处理

loaded也不是说外部不能使用, 只是按照Net+BRV的形式根本无需使用, 因为默认自动化处理, 但是很多开发者出于各种原因可能并不会使用我的所有框架, 这种情况请自己处理这些细节问题

多阅读学习demo示例代码你写的代码会更简单

**Comment by Lanxiong** [comment]
好的 我再看看 
我还没用你的框架 
他们说你的库很牛逼 
刚好有些有自己封装过

我来学习一下 
看看大佬的封装思路
和一些场景的匹配度 

实在不行也可以自己加点扩展函数
满足当前应用的一些场景

**Comment by liangjingkanji** [comment]
你将你的下拉刷新换成PageRefreshLayout使用其showError也可以. 如果不行就自己判断loaded

**Comment by liangjingkanji** [comment]
我认为判断下loaded和给showError加个参数, 区别意义不大

PageRefreshLayout可以使默认showError是无效的(在loaded过情况下), 但是SateLayout不可能这样

**Comment by liangjingkanji** [comment]
牛逼不牛逼自己看自己如何使用吧, 这是开源项目你可以自己fork二次修改, 不过建议保持追踪因为本项目会持续修复bug
