### ISSUE TITLE
结合RecyclerView使用出现无法显示内容的问题

### ISSUE THREAD

**Issue by zrmomo** [liangjingkanji/StateLayout#32]
Loading状态调用showLoading()，数据回来后调用showContent()无法显示内容。
![image](https://github.com/liangjingkanji/StateLayout/assets/56543271/61aa1af9-a4f2-4c85-9ed4-181f7fc02b54)

改变xml中的嵌套层级可以正常显示：
![image](https://github.com/liangjingkanji/StateLayout/assets/56543271/cebcf7a1-62d0-49fa-aca3-09fba5717c7f)
![image](https://github.com/liangjingkanji/StateLayout/assets/56543271/7599e2c5-d43c-48f9-93de-864f784ebe85)

**Comment by liangjingkanji** [comment]
`prl_state`是什么布局?

看起来是`StateLayout`把RecyclerView挡住了, 不是很明白你这么写的原因, 但是你认为缺省页是`showContent`后会自动消失

你看下demo或者文档到底是怎么用的吧, 缺省页StateLayout只会切换他内部的布局

另外关于列表缺省页可以看看另一个框架[BRV](https://github.com/liangjingkanji/BRV), 他有个PageRefreshLayout支持缺省页更好

**Comment by liangjingkanji** [comment]
如果还有疑问请fork仓库复现问题, 猜来猜去我猜不出来问题

**Comment by zrmomo** [comment]
好的强哥感谢回复 我再研究研究文档
