### ISSUE TITLE
请问有获取page正在显示的状态页面的方法吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/StateLayout#34]
比如`page.isShowContent():Boolean / page.isShowEmpty():Boolean`这种，可以获取当前正在显示的缺省页，方便在外部调用刷新方法😂

**Comment by SaltedFish-Extreme** [comment]
结合BRV用的，好像没看到有这种方法

**Comment by liangjingkanji** [comment]
`PageRefreshLayout.status` 当前缺省页状态

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 不是，你可能理解错我的意思了，我想知道有没有 获取当前正在显示的缺省页的方法😂比如空页面或者错误页面

**Comment by SaltedFish-Extreme** [comment]
而且好像只有 `PageRefreshLayout.state` 方法，是智能刷新里面的方法，没有获取当前缺省页状态的status

**Comment by SaltedFish-Extreme** [comment]
哦，我好像看源码找着了，是`stateLayout.status`😂
