### ISSUE TITLE
建议添加showContent的动画效果

### ISSUE THREAD

**Issue by hyx0804xiaokeai** [liangjingkanji/StateLayout#4]
知乎会在 显示content的时候 有一个渐显动画，觉得效果不错

**Comment by liangjingkanji** [comment]
抱歉, 没收到消息通知

创建动画使用生命周期函数中对View进行处理即可: https://liangjingkanji.github.io/StateLayout/lifecycle.html

update 1.1.0. 新增 `onContent` 生命周期, 你在里面自己对View创建你想要的动画(比如AlphaAnimation实现渐变动画), 我无法内部替你实现动画, 因为不同的应用需求不同.
