### ISSUE TITLE
希望能支持一些页面切换动画

### ISSUE THREAD

**Issue by ZXHHYJ** [liangjingkanji/StateLayout#5]
要是有时间可以考虑这个功能

**Comment by liangjingkanji** [comment]
本身这个框架就是支持自定义动画. 而且缺省页切换, 一般都是无动画. 因为有动画影响页面秒开. 最多也就有个渐变动画吧, 这个实现代码才一行还要封装么

**Comment by liangjingkanji** [comment]
自定义动画: https://liangjingkanji.github.io/StateLayout/animation/

**Comment by liangjingkanji** [comment]
自定义动画: https://liangjingkanji.github.io/StateLayout/animation/
