### ISSUE TITLE
配置变更后无法保存最后状态

### ISSUE THREAD

**Issue by ZXHHYJ** [liangjingkanji/StateLayout#6]
在fragment使用时发生配置变更后状态变回默认content状态，若在loading状态下发生配置变更后变回content状态，明显不符合预期

**Comment by liangjingkanji** [comment]
好的，等我过阵子起床处理可以不

**Comment by ZXHHYJ** [comment]
好家伙，这个点还没睡，幸苦幸苦

**Comment by liangjingkanji** [comment]
Duplicate of #7
