### ISSUE TITLE
showXXX等方法重复执行动画

### ISSUE THREAD

**Issue by ZXHHYJ** [liangjingkanji/StateLayout#8]
比如showContent方法，每次调用都执行一次showContent的动画。
不应该判断当前显示的页面是不是content页面，如果不是 再显示content页面并执行动画吗？

**Comment by liangjingkanji** [comment]
当初考虑的是调用次数取决于开发者调用set*函数次数. 你的意思是我让set*在同一状态下重复调用是无效的执行是吧?

**Comment by ZXHHYJ** [comment]
对！

**Comment by liangjingkanji** [comment]
不太行, 因为考虑到缺省页可以进行差异化显示, 比如通过`set*`函数传参, 在`on**`函数中进行参数判断展示差异化的缺省页. 

重复调用on*函数不能算bug, 毕竟开发者自己调用的, 你可以自己判断`StateLayout.status`来是否进行重复调用

**Comment by liangjingkanji** [comment]
就比如常见的错误页分为
1. 无网络错误
2. 服务器错误
3. 数据解析错误
不同的错误展示的文字和图片不同
