### ISSUE TITLE
使用文档打不开

### ISSUE THREAD

**Issue by gegeName** [liangjingkanji/StateLayout#9]
使用文档打不开

**Comment by gegeName** [comment]
备用也打不开

**Comment by gegeName** [comment]
如何拿到各个缺省页中的控件。因为我想加载一个GIF图片。

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/132271867-6ee3e1ea-0e4c-4221-b4a4-8dce113f1694.png)

**Comment by liangjingkanji** [comment]
主文档你打开是什么页面, 能否截图发我. 应该是部分地区和谐了GitHub静态文档域名

**Comment by gegeName** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/132272070-d63b32fa-1160-4842-8672-b5f661a4727b.png)
](url)

**Comment by gegeName** [comment]
这个是备用的[
![image](https://user-images.githubusercontent.com/20966610/132272161-3b970fc2-cd5d-4f87-bcd8-04ea51bb7d8b.png)
](url)

**Comment by liangjingkanji** [comment]
> 这个是备用的[ ![image](https://user-images.githubusercontent.com/20966610/132272161-3b970fc2-cd5d-4f87-bcd8-04ea51bb7d8b.png) ](url)

好的, 尽快修复备用文档地址

**Comment by liangjingkanji** [comment]
备用文档地址已修复
